name: Explore GitHub Context

on: [workflow_dispatch]

jobs:
  explore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
