name: Explore GitHub Context

on: workflow_dispatch

jobs:
  explore:
    runs-on: ubuntu-latest
    steps:

      - name: Dump GitHub context
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)"
          echo '${{ toJSON(github) }}'

